name: Kotlin-Native CI/CD

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
    # Prevent duplicate runs for PR from same repository
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    # Run on push events or PR events from same repository (skip only external forks)
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Verify Kotlin-native configuration
      run: |
        ./gradlew --version
        ./gradlew verifyKotlinNativeSetup --no-daemon
    
    - name: Run tests
      run: |
        ./gradlew :shared:test --no-daemon
    
    - name: Generate test report
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Kotlin-Native Tests
        path: Poker-Basic/build/test-results/test/*.xml
        reporter: java-junit
        fail-on-error: false
    
    - name: Upload test results
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: Poker-Basic/build/test-results/test/
        retention-days: 30
    
    - name: Build with Gradle
      run: |
        ./gradlew :shared:fatJar --no-daemon
        
  package:
    runs-on: ubuntu-latest
    needs: test
    # Run on push events or PR events from same repository (skip only external forks)
    if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.event_name == 'pull_request')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Package application with Gradle
      run: |
        ./gradlew :shared:fatJar --no-daemon
    
    - name: Verify JAR was created
      run: |
        cd Poker-Basic/build/libs
        ls -la *.jar
        echo "Verifying JAR is executable..."
        java -jar *-fat.jar --help || echo "JAR created successfully (help command may not be implemented)"
    
    - name: Determine artifact retention
      id: retention
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          PR_NUMBER="${{ github.event.number }}"
          echo "retention_days=14" >> $GITHUB_OUTPUT
          echo "artifact_name=pokermon-kotlin-native-pr-${PR_NUMBER}" >> $GITHUB_OUTPUT
          echo "apk_artifact_name=pokermon-android-pr-${PR_NUMBER}" >> $GITHUB_OUTPUT
        else
          echo "retention_days=90" >> $GITHUB_OUTPUT
          echo "artifact_name=pokermon-kotlin-native" >> $GITHUB_OUTPUT
          echo "apk_artifact_name=pokermon-android" >> $GITHUB_OUTPUT
        fi
    
    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.retention.outputs.artifact_name }}
        path: Poker-Basic/build/libs/*.jar
        retention-days: ${{ steps.retention.outputs.retention_days }}

  android-build:
    runs-on: ubuntu-latest
    needs: [test, package]
    # Run on push events or PR events from same repository (skip only external forks)
    if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.event_name == 'pull_request')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Cache Android SDK
      uses: actions/cache@v4
      with:
        path: |
          ~/android-sdk
        key: android-sdk-34-${{ runner.os }}-${{ hashFiles('android/build.gradle') }}
        restore-keys: |
          android-sdk-34-${{ runner.os }}-
    
    - name: Setup Android SDK (Manual)
      id: setup-android
      run: |
        echo "=== Setting up Android SDK manually for maximum reliability ==="
        
        # Set up Android SDK directory
        export ANDROID_HOME=$HOME/android-sdk
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
        echo "PATH=$PATH" >> $GITHUB_ENV
        
        # Check if SDK is already cached
        if [ -d "$ANDROID_HOME/cmdline-tools/latest" ] && [ -d "$ANDROID_HOME/platforms/android-34" ]; then
          echo "Android SDK found in cache, verifying setup..."
          sdkmanager --version
          sdkmanager --list_installed
          echo "=== Android SDK restored from cache successfully ==="
          exit 0
        fi
        
        # Create SDK directory structure
        mkdir -p $ANDROID_HOME/cmdline-tools
        mkdir -p $ANDROID_HOME/licenses
        
        # Download and install command line tools (latest version)
        echo "Downloading Android cmdline-tools..."
        cd $ANDROID_HOME/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11479570_latest.zip
        unzip -q commandlinetools-linux-11479570_latest.zip
        mv cmdline-tools latest
        rm commandlinetools-linux-11479570_latest.zip
        
        # Pre-accept all Android SDK licenses to avoid interactive prompts
        echo "Pre-accepting Android SDK licenses..."
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/intel-android-extra-license
        echo "33b6a2b64607f11b759f320ef9dff4ae5c47d97a" > $ANDROID_HOME/licenses/google-gdk-license
        echo "d975f751698a77b662f1254ddbeed3901e976f5a" > $ANDROID_HOME/licenses/mips-android-sysimage-license
        
        # Verify sdkmanager is working
        echo "Testing sdkmanager installation..."
        sdkmanager --version
        
        # Install required Android SDK components
        echo "Installing Android SDK components..."
        sdkmanager --install "platforms;android-34"
        sdkmanager --install "build-tools;34.0.0"
        sdkmanager --install "ndk;25.2.9519653"
        sdkmanager --install "platform-tools"
        
        # List installed packages for verification
        echo "Installed Android SDK components:"
        sdkmanager --list_installed
        
        echo "=== Android SDK setup completed successfully ==="
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build Android APK with Kotlin-native
      run: |
        echo "Starting Android APK build with Kotlin-native..."
        echo "Gradle version:"
        ./gradlew --version
        
        echo "Android SDK verification:"
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "Available platforms:"
        ls -la "$ANDROID_HOME/platforms/" || echo "No platforms found"
        echo "Available build-tools:"
        ls -la "$ANDROID_HOME/build-tools/" || echo "No build tools found"
        
        echo "SDK Manager packages:"
        sdkmanager --list_installed | head -20
        
        echo "Building APK with Kotlin-native source integration..."
        ./gradlew :android:assembleDebug --no-daemon --stacktrace --info || {
          echo "=== BUILD FAILED - Diagnostic Information ==="
          echo "Android SDK location: $ANDROID_HOME"
          echo "Environment variables:"
          env | grep ANDROID
          echo "Gradle daemon status:"
          ./gradlew --status || true
          echo "=== END DIAGNOSTIC INFO ==="
          exit 1
        }
    
    - name: Verify APK was created
      run: |
        ls -la android/build/outputs/apk/debug/
        echo "APK created successfully"
    
    - name: Determine artifact retention
      id: retention
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          PR_NUMBER="${{ github.event.number }}"
          echo "retention_days=14" >> $GITHUB_OUTPUT
          echo "apk_artifact_name=pokermon-android-pr-${PR_NUMBER}" >> $GITHUB_OUTPUT
        else
          echo "retention_days=90" >> $GITHUB_OUTPUT
          echo "apk_artifact_name=pokermon-android" >> $GITHUB_OUTPUT
        fi
    
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.retention.outputs.apk_artifact_name }}
        path: android/build/outputs/apk/debug/*.apk
        retention-days: ${{ steps.retention.outputs.retention_days }}
