name: Java CI/CD

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Verify Maven configuration
      run: |
        cd Poker-Basic
        mvn --version
        mvn help:effective-pom -q
    
    - name: Run tests
      run: |
        cd Poker-Basic
        mvn clean test -B
    
    - name: Generate test report
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Maven Tests
        path: Poker-Basic/target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: false
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: Poker-Basic/target/surefire-reports/
        retention-days: 30
    
    - name: Build with Maven
      run: |
        cd Poker-Basic
        mvn clean compile -B
        
  package:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Package application
      run: |
        cd Poker-Basic
        mvn clean package -DskipTests -B
    
    - name: Verify JAR was created
      run: |
        cd Poker-Basic/target
        ls -la *.jar
        echo "Verifying JAR is executable..."
        java -jar *.jar --help || echo "JAR created successfully (help command may not be implemented)"
    
    - name: Determine artifact retention
      id: retention
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          PR_NUMBER="${{ github.event.number }}"
          echo "retention_days=14" >> $GITHUB_OUTPUT
          echo "artifact_name=poker-game-jar-pr-${PR_NUMBER}" >> $GITHUB_OUTPUT
          echo "apk_artifact_name=poker-game-apk-pr-${PR_NUMBER}" >> $GITHUB_OUTPUT
        else
          echo "retention_days=90" >> $GITHUB_OUTPUT
          echo "artifact_name=poker-game-jar" >> $GITHUB_OUTPUT
          echo "apk_artifact_name=poker-game-apk" >> $GITHUB_OUTPUT
        fi
    
    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.retention.outputs.artifact_name }}
        path: Poker-Basic/target/*.jar
        retention-days: ${{ steps.retention.outputs.retention_days }}

  android-build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build Android APK
      run: ./gradlew :android:assembleDebug --no-daemon --stacktrace
    
    - name: Verify APK was created
      run: |
        ls -la android/build/outputs/apk/debug/
        echo "APK created successfully"
    
    - name: Determine artifact retention
      id: retention
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          PR_NUMBER="${{ github.event.number }}"
          echo "retention_days=14" >> $GITHUB_OUTPUT
          echo "apk_artifact_name=poker-game-apk-pr-${PR_NUMBER}" >> $GITHUB_OUTPUT
        else
          echo "retention_days=90" >> $GITHUB_OUTPUT
          echo "apk_artifact_name=poker-game-apk" >> $GITHUB_OUTPUT
        fi
    
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.retention.outputs.apk_artifact_name }}
        path: android/build/outputs/apk/debug/*.apk
        retention-days: ${{ steps.retention.outputs.retention_days }}

  release:
    runs-on: ubuntu-latest
    needs: [test, package, android-build]
    if: startsWith(github.ref, 'refs/heads/alpha-') || startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: poker-game-jar
        path: ./artifacts
    
    - name: Download APK artifact
      uses: actions/download-artifact@v4
      with:
        name: poker-game-apk
        path: ./artifacts
    
    - name: Get version from pom.xml
      id: version
      run: |
        cd Poker-Basic
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Project version: $VERSION"
    
    - name: Determine release type
      id: release_type
      run: |
        if [[ "${{ github.ref }}" == refs/heads/alpha-* ]]; then
          echo "type=alpha" >> $GITHUB_OUTPUT
          echo "prerelease=true" >> $GITHUB_OUTPUT
          echo "tag_name=alpha-${{ steps.version.outputs.version }}-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
          echo "release_name=Alpha Test Release ${{ steps.version.outputs.version }}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          echo "type=release" >> $GITHUB_OUTPUT
          echo "prerelease=false" >> $GITHUB_OUTPUT
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "release_name=Release ${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "type=development" >> $GITHUB_OUTPUT
          echo "prerelease=true" >> $GITHUB_OUTPUT
          echo "tag_name=dev-${{ steps.version.outputs.version }}-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
          echo "release_name=Development Build ${{ steps.version.outputs.version }}" >> $GITHUB_OUTPUT
        fi
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.release_type.outputs.tag_name }}
        name: ${{ steps.release_type.outputs.release_name }}
        body: |
          ## Poker Game Educational Project
          
          ### Release Information
          - **Version**: ${{ steps.version.outputs.version }}
          - **Build Date**: ${{ github.event.head_commit.timestamp }}
          - **Commit**: ${{ github.sha }}
          - **Branch**: ${{ github.ref_name }}
          
          ### What's Included
          - **Desktop JAR**: Full-featured poker game with modern JavaFX UI and console mode
          - **Android APK**: Mobile version with Jetpack Compose interface
          - Complete educational codebase demonstrating code improvement practices
          
          ### Quick Start
          
          #### Desktop (JAR)
          ```bash
          # Download the JAR file
          # Modern UI (Default)
          java -jar pokermon-${{ steps.version.outputs.version }}.jar
          
          # Console Version for Testing
          java -jar pokermon-${{ steps.version.outputs.version }}.jar --basic
          ```
          
          #### Android (APK)
          - Download and install the APK file on your Android device
          - Enable "Install from unknown sources" if required
          - Supports Android 5.0 (API 21) and higher
          
          ### Requirements
          - **Desktop**: Java 17 or higher
          - **Android**: Android 5.0+ (API 21+)
          
          ---
          
          This is an educational project demonstrating professional software development practices and code improvement techniques.
        draft: false
        prerelease: ${{ steps.release_type.outputs.prerelease }}
        files: |
          ./artifacts/pokermon-${{ steps.version.outputs.version }}.jar
          ./artifacts/*.apk
        token: ${{ secrets.GITHUB_TOKEN }}