name: Copilot Setup Steps

on:
  workflow_dispatch:
  
jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Install dependencies
      run: |
        cd Poker-Basic
        mvn clean compile -B
    
    - name: Verify project setup
      run: |
        cd Poker-Basic
        mvn --version
        mvn help:effective-pom -q
        echo "Project dependencies installed successfully"
        echo "Environment ready for GitHub Copilot coding agent"